name = "jsonhero-io"
compatibility_date = "2024-06-26"
main = "dist/worker.js"

route = "jsonhero.io/*"
account_id = "0e405dda228e3448f1366acb0bc341ef"
kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "e517c369774a443eba95afff9128f7b6" }
]

[site]
bucket = "./public"

[build]
watch_dir = "build/index.js"

[dev]
port = 8002

[vars]
GRAPH_JSON_COLLECTION = "jsonhero-prod"

[env.dev]
account_id = "c974caaaa18255c03f1771097bade662"
kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "a90ce96eb26c4989a1232db27e864ed6" }
]

[env.dev.vars]
GRAPH_JSON_COLLECTION = "jsonhero-dev"

# Secrets
# [SESSION_STORAGE]
# [GRAPH_JSON_API_KEY]
# [APIHERO_PROJECT_KEY]
